version: '3.8'
services:
  vault:
    container_name: vault_stellar_sign
    build: .
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
#    volumes:
#      - ./vault/plugins:/vault/plugins
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -dev -dev-root-token-id=root -dev-plugin-dir=/vault/plugins